# Mode developpement : applique automatiquement par docker compose up
services:
  app:
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    command: ["npx", "nodemon", "app.js"]
    restart: "no"

  db:
    ports:
      - "3306:3306"
    restart: "no"

  redis:
    ports:
      - "6379:6379"
    restart: "no"
