sonar.projectKey=SEBonduel_Retro-Arcade-Leaderboard
sonar.organization=sebonduel
sonar.projectName=Retro-Arcade-Leaderboard

sonar.sources=.
sonar.exclusions=node_modules/**,k6/**,grafana/**,prometheus/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
